### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WeiYangBin** [MeetzhDing/Chinese-VQA#2]
```
Traceback (most recent call last):
  File "/Users/weiyangbin/ChineseVQA/extract_fc7.py", line 108, in <module>
    main()
  File "/Users/weiyangbin/ChineseVQA/extract_fc7.py", line 38, in main
    graph_def.ParseFromString(vgg16raw)
google.protobuf.message.DecodeError: Error parsing messag
```

**Comment by WeiYangBin** [comment]
已经解决，下载*** .tfmodel*** 文件
